# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01fd29323892e9f46738bfd3a2d4a4a699748c41ccc0f1bfce3c0f6942626ef057bab8a7bac4dbf41d8747d0bc9099fa76b90493dbf07887b633a209ee045033

test:
  secret_key_base: 867c718111700fe1e29f9fe2acaf08cf923048860c478188945b854bc00e138294e70bd0ef1f87a41878e737c4c5a5d628f8b3212bab6b78f6f753007403db4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
